---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-deploy
  namespace: codeserver
  labels:
    app: code
    name: code-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
      name: code-po
  template:
    metadata:
      labels:
        app: code
        name: code-po
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: workspace-vol
        persistentVolumeClaim:
          claimName: codeserver-pvc
      containers:
      - name: code-container
        image: linuxserver/code-server:amd64-4.92.2
        envFrom:
        - configMapRef:
            name: code-server-config
        - secretRef:
            name: code-server-secret
        env: 
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: workspace-vol
          mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: code-svc
  namespace: codeserver
  labels:
    app: code
    name: code-svc
spec:
  type: ClusterIP
  selector:
    app: code
    name: code-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-ing
  namespace: codeserver
  labels: 
    app: code
    name: code-ing
spec:
  ingressClassName: nginx
  rules:
  - host: code.188.166.198.122.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: code-svc
            port: 
              number: 8443

