---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  namespace: codeserver
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
  SUDO_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"