---
apiVersion: v1
kind: Namespace
metadata:
  name: dovns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: dovns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dov
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
        ports:
        - containerPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-hpa
  namespace: dovns
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef: 
    apiVersion: apps/vz
    kind: Deployment
    name: dov-deploy
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target: 
        type: Utilization
        averageUtilization: 20

---
apiVersion: v1
kind: Service
metadata:
  name: dov-hsvc
  namespace: dovns
  labels: 
    app: dov
    name: dov-hsvc
spec:
  type: ClusterIP
  selector: 
    app: dov
    name: dov-po
  ports: 
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dov-sts
  namespace: dovns
spec:
  replicas: 3
  serviceName: dov-hsvc
  selector:
    matchLabels:
      app: dov
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
        ports:
        - containerPort: 3000